//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendeles_has_Termekek
    {
        public int Rendeles_Rendelesid { get; set; }
        public int Termekek_Termekekid { get; set; }
    }
}
