//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termekek
    {
        public Nullable<int> Termekid { get; set; }
        public string Termeknev { get; set; }
        public Nullable<int> Termekar { get; set; }
        public string Termekleiras { get; set; }
        public string Kep { get; set; }
    }
}
