//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_WPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VideoGameShopEntities : DbContext
    {
        public VideoGameShopEntities()
            : base("name=VideoGameShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminok> Adminoks { get; set; }
        public virtual DbSet<Felhasznalo> Felhasznaloes { get; set; }
        public virtual DbSet<Jogosultsag> Jogosultsags { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Adminok_has_Rendeles> Adminok_has_Rendeles { get; set; }
        public virtual DbSet<Felhasznalo_has_Rendeles> Felhasznalo_has_Rendeles { get; set; }
        public virtual DbSet<Rendeles_has_Termekek> Rendeles_has_Termekek { get; set; }
        public virtual DbSet<Termekek> Termekeks { get; set; }
    }
}
